pipeline {

	agent none

	stages{
			agent{
				docker{
					image 'python:2.7.16-slim'
					args '--user root'
				}
			}

		
			stage("build"){

				when{
					changeset "**/vote/**"
				}	



			steps{
				echo 'Compiling vote app'
				dir('vote'){
					sh 'pip install -r requirements.txt'
				}
			}
		}


			stage("test"){
				when{
					changeset "**/vote/**"
				}

			agent{
				docker{
					image 'python:2.7.16-slim'
					args '--user root'
				}
			}
			
			steps{
				echo 'Running Unit Tests on worker app'
				dir('vote'){
				sh 'pip install -r requirements.txt'
				sh 'nosetests -v'
				}
			}
		}



			stage('docker-package'){
				agent any
				when{
					changeset "**/vote/**"
					branch 'master'
				}
				steps{
					echo 'Packaging vote app with docker'
					script{
						docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin'){
						def workerImage = docker.build("rsdroid/vote:v${env.BUILD_ID}", "./vote")
						workerImage.push()
						workerImage.push("${env.BRANCH_NAME}")
						workerImage.push("latest")
						}
					}
				}
			}
		}
	
	post{
		always{
			echo 'Building multibranch pipeline for worker is completed..'
		}
	}
}
