version: '3.8'

networks:
  instavote:
    driver: bridge

volumes:
  db-data:

services:
  vote:
    image: rsdroid/vote:batvssuper
    ports:
      - 5000:80
    networks:
      - instavote
    build: ./vote 
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      - instavote

  db: 
    image: postgres:9.4
    volumes: 
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust      

  result:
    image: rsdroid/result:batvssuper
    build: ./result
    ports: 
      - 5001:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: rsdroid/worker:latest
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote    
